// Generated by: chatgpt
// Date: 2023-10-04
// Description: This program retrieves and displays information about a process in Linux using the /proc filesystem.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "funciones.h"

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Uso: %s <PID>\n", argv[0]);
        return 1;
    }else if (argc == 2)
    {
        print_pid(argv[1]);
        return 0;
    }else if (argc > 2)
    {
        fprintf(stderr, "Error: Demasiados argumentos.\n");
        return 1;
    }    

}