// Generated by: chatgpt
// Date: 2023-10-04
// Description: This program retrieves and displays information about a process in Linux using the /proc filesystem.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "funciones.h" // Incluye las definiciones de las funciones de infoPid.c

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Uso: %s [-l] <PID> [PID...]\n", argv[0]);
        return 1;
    }else if (strcmp(argv[1], "-l") == 0) {
        if (argc < 3) {
            fprintf(stderr, "Error: Debe ingresar al menos un PID después de -l. \nEjemplo: ./psinfo -l 2093\n");
            return 1;
        }
        print_multiple_pids(argc - 2, &argv[2]); // Procesar múltiples PIDs
        return 0;
    } else if (argc == 2) {
        // Manejar un solo PID
        ProcInfo info;
        if (get_proc_info(argv[1], &info) == 0) {
            print_proc_info(&info); // Imprimir información del proceso
        } else {
            fprintf(stderr, "Error: No se pudo obtener información para el PID %s.\n", argv[1]);
        }
        return 0;
    } else {
        // Mostrar error si hay más de un PID sin usar -l
        fprintf(stderr, "Error: Demasiados argumentos, use la opción -l para múltiples PIDs.\n");
        return 1;
    }
}